baseURL = "/"
languageCode = "en-us"
title = "WellsFargo Application Modernization Cookbook"
copyright = " Wells Fargo, All Rights Reserved, Confidential"
theme = "hugo-theme-docdock"
publishDir = "public"
pygmentsCodeFences = true
pygmentsStyle = "friendly"
enableGitInfo = true
googlefonts = "https://fonts.googleapis.com/css?family=Merriweather|Fira+Mono|Droid+Sans"

[params]
  themeStyle = "original"
  description = "Application Modernization Cookbook"
  noCategoryLink = true
  showVisitedLinks = false
  disableSearch = false
  disableHomeIcon = true
  ordersectionsby = "weight"
  ignoreFiles = [ "\\.adoc$" , "\\.docx$" ]
  disableNavChevron = true
  menushortcutsnewtab = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
  extensions = [ "DefinitionLists", ]

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-fw fa-info'></i> About"
identifier = "about"
url = "/about"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.wellsfargo.com/app-ebst/wf-starter-cookbook"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-fw fa-download'></i> Download"
identifier = "download"
url = "https://github.wellsfargo.com/app-ebst/wf-starter-cookbook/repository/master/archive.zip"
weight = 12

[[menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
identifier = "credits"
url = "/credits"
weight = 13

[[menu.shortcuts]]
pre = "<h5>&nbsp;</h5>"
name = "<i class='fa fa-tag'></i>&nbsp;&nbsp;All Tags"
url = "/tags/"
weight = 14

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
